FROM ericlendvai/harbour_curl_hb-orm_hb-vfp_hb-fastcgi_apache_odbc-postgresql:latest AS builder

#ARG FakeOptionToForceReDownloadingRepos_ChangeTheFollowingValue 100
WORKDIR /src
RUN git clone https://github.com/EricLendvai/DataWharf.git

ENV HB_COMPILER gcc

# Build DataWharf
WORKDIR /src/DataWharf
RUN mkdir -p build/lin64/gcc/release/
ENV EXEName DataWharf
ENV BuildMode release
ENV SiteRootFolder /var/www/Harbour_websites/fcgi_DataWharf/
RUN chmod +x ./BuildEXE.sh
RUN ./BuildEXE.sh

# ----------------------------------------------------------------------------------------------
FROM ubuntu:22.04

## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# Used by running apps to detect if inside a docker container. Testing for existence of /.dockerenv may not always work.
ENV InDocker=True

RUN apt-get update && apt-get install -y apt-utils

RUN apt-get install -y \
        libfcgi-dev \
        libapache2-mod-fcgid \
        git \
        build-essential \
        unixodbc-dev \
        apache2 \
        libgpm2 \
        gnupg \
        wget \
        psmisc \
        libcurl4-openssl-dev

RUN apt-get update && apt-get -y upgrade

# Had to run the following dependency install separatly
RUN apt-get install -y libssl-dev

# install Postgresql odbc driver
RUN apt-get -y install odbc-postgresql

RUN a2enmod rewrite
RUN mkdir -p /var/www/Harbour_websites/fcgi_DataWharf/apache-logs/

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

COPY ./FilesForPublishedWebsites/LinuxApache2/DataWharf.conf /etc/apache2/sites-enabled/000-default.conf

RUN mkdir -p /var/www/Harbour_websites/fcgi_DataWharf/backend/
COPY ./config_demo.txt /var/www/Harbour_websites/fcgi_DataWharf/backend/config.txt

#RUN cp /src/DataWharf/build/lin64/gcc/release/DataWharf.exe /var/www/Harbour_websites/fcgi_DataWharf/backend/FCGIDataWharf.exe
 COPY --from=builder /src/DataWharf/build/lin64/gcc/release/DataWharf.exe /var/www/Harbour_websites/fcgi_DataWharf/backend/FCGIDataWharf.exe

COPY ./FilesForPublishedWebsites/website /var/www/Harbour_websites/fcgi_DataWharf/website

RUN chown -R www-data:www-data /var/www/Harbour_websites

EXPOSE 80 

CMD apache2ctl start & sleep infinity
