FROM ericlendvai/harbour_curl_hb-orm_hb-vfp_hb-fastcgi_apache_odbc-postgresql:latest

# "ADD https://api.github.com/repos/...." Logic to help avoid cache on git clone commands

WORKDIR /src

ADD https://api.github.com/repos/EricLendvai/DataWharf/git/refs/heads/main RepoVersionDataWharf.json
RUN git clone https://github.com/EricLendvai/DataWharf.git

ENV HB_COMPILER gcc

# Build DataWharf
WORKDIR /src/DataWharf
RUN mkdir -p build/lin64/gcc/release/
ENV EXEName DataWharf
ENV BuildMode release
ENV SiteRootFolder /var/www/Harbour_websites/fcgi_DataWharf/
RUN chmod +x ./BuildEXE.sh
RUN ./BuildEXE.sh

RUN a2enmod rewrite
RUN mkdir -p /var/www/Harbour_websites/fcgi_DataWharf/apache-logs/

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

COPY ./FilesForPublishedWebsites/LinuxApache2/DataWharf.conf /etc/apache2/sites-enabled/000-default.conf

RUN mkdir -p /var/www/Harbour_websites/fcgi_DataWharf/backend/
COPY ./config_demo.txt /var/www/Harbour_websites/fcgi_DataWharf/backend/config.txt
RUN cp /src/DataWharf/build/lin64/gcc/release/DataWharf.exe /var/www/Harbour_websites/fcgi_DataWharf/backend/FCGIDataWharf.exe

COPY ./FilesForPublishedWebsites/website /var/www/Harbour_websites/fcgi_DataWharf/website

RUN chown -R www-data:www-data /var/www/Harbour_websites

EXPOSE 80 

CMD apache2ctl start & sleep infinity
