FROM ubuntu:22.04 AS builder

## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# Used by running apps to detect if inside a docker container. Testing for existence of /.dockerenv may not always work.
ENV InDocker=True

RUN apt-get update && apt-get install -y apt-utils

RUN apt-get install -y \
        libfcgi-dev \
        libapache2-mod-fcgid \
        git \
        build-essential \
        unixodbc-dev \
        apache2 \
        libgpm2 \
        gnupg \
        wget \
        psmisc \
        libcurl4-openssl-dev

RUN apt-get update && apt-get -y upgrade

# Had to run the following dependency install separatly
RUN apt-get install -y libssl-dev

# install Postgresql odbc driver
RUN apt-get -y install odbc-postgresql

# install harbour from src
RUN mkdir /src
WORKDIR /src
RUN git clone --branch master https://github.com/harbour/core.git harbour
WORKDIR /src/harbour

ENV HB_WITH_CURL=/usr/include/x86_64-linux-gnu/
ENV HB_WITH_OPENSSL=/usr/include/openssl/

# Will request the make app to use up to 8 core.
RUN make -j 8 install

#To fix symlinks
RUN ldconfig

# Make some additional supporting libs
WORKDIR /src
RUN git clone https://github.com/EricLendvai/Harbour_FastCGI/
RUN git clone https://github.com/EricLendvai/Harbour_VFP/
RUN git clone https://github.com/EricLendvai/Harbour_ORM/

#Will be used for future web apps builds and when building hb_orm
ENV HB_VFP_ROOT /src/Harbour_VFP/
ENV HB_ORM_ROOT /src/Harbour_ORM/
ENV HB_FASTCGI_ROOT /src/Harbour_FastCGI/

ENV HB_COMPILER gcc

ENV BuildMode release

WORKDIR /src/Harbour_VFP
RUN chmod +x ./BuildLIB.sh
ENV LIBName hb_vfp
RUN ./BuildLIB.sh

WORKDIR /src/Harbour_ORM
RUN chmod +x ./BuildLIB.sh
ENV LIBName hb_orm
RUN ./BuildLIB.sh

#also build debug libraries
ENV BuildMode debug

WORKDIR /src/Harbour_VFP
ENV LIBName hb_vfp
RUN ./BuildLIB.sh

WORKDIR /src/Harbour_ORM
ENV LIBName hb_orm
RUN ./BuildLIB.sh


#ARG FakeOptionToForceReDownloadingRepos_ChangeTheFollowingValue 100
WORKDIR /src
RUN git clone https://github.com/EricLendvai/DataWharf.git

ENV HB_COMPILER gcc

# Build DataWharf
WORKDIR /src/DataWharf
RUN mkdir -p build/lin64/gcc/release/
ENV EXEName DataWharf
ENV BuildMode release
ENV SiteRootFolder /var/www/Harbour_websites/fcgi_DataWharf/
RUN chmod +x ./BuildEXE.sh
RUN ./BuildEXE.sh

# ----------------------------------------------------------------------------------------------
FROM ubuntu:22.04

## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# Used by running apps to detect if inside a docker container. Testing for existence of /.dockerenv may not always work.
ENV InDocker=True

RUN apt-get update && apt-get install -y apt-utils

RUN apt-get install -y \
        libfcgi-dev \
        libapache2-mod-fcgid \
        git \
        build-essential \
        unixodbc-dev \
        apache2 \
        libgpm2 \
        gnupg \
        wget \
        psmisc \
        libcurl4-openssl-dev

RUN apt-get update && apt-get -y upgrade

# Had to run the following dependency install separatly
RUN apt-get install -y libssl-dev

# install Postgresql odbc driver
RUN apt-get -y install odbc-postgresql

RUN a2enmod rewrite
RUN mkdir -p /var/www/Harbour_websites/fcgi_DataWharf/apache-logs/

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

COPY ./FilesForPublishedWebsites/LinuxApache2/DataWharf.conf /etc/apache2/sites-enabled/000-default.conf

RUN mkdir -p /var/www/Harbour_websites/fcgi_DataWharf/backend/
COPY ./config_demo.txt /var/www/Harbour_websites/fcgi_DataWharf/backend/config.txt

#RUN cp /src/DataWharf/build/lin64/gcc/release/DataWharf.exe /var/www/Harbour_websites/fcgi_DataWharf/backend/FCGIDataWharf.exe
 COPY --from=builder /src/DataWharf/build/lin64/gcc/release/DataWharf.exe /var/www/Harbour_websites/fcgi_DataWharf/backend/FCGIDataWharf.exe

COPY ./FilesForPublishedWebsites/website /var/www/Harbour_websites/fcgi_DataWharf/website

RUN chown -R www-data:www-data /var/www/Harbour_websites

EXPOSE 80 

CMD apache2ctl start & sleep infinity
