//As of DataWharf 3, its own configuration is defined using a "DataWharf" application managed in DataWharf itself.
function Config()
return ;
{"HarbourORMVersion"=>4.2,;
 "DataWharfVersion"=>3.6,;
 "Backend"=>"PostgreSQL",;
 "GenerationTime"=>"2024-01-31T18:15:05.506Z",;
 "GenerationSignature"=>"88c42277-4660-456c-80e0-883f1ca1ee9e",;
 "Tables"=>;
    {"public.APIAccessEndpoint"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_APIToken"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.APIToken","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_APIEndpoint"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.APIEndpoint","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"}};
                                 ,"Indexes"=>;
        {"fk_apiendpoint"=>{"Expression"=>"fk_APIEndpoint"};
        ,"fk_apitoken"   =>{"Expression"=>"fk_APIToken"}}};
    ,"public.APIEndpoint"=>{"Fields"=>;
        {"pk"    =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"  =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"  =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"Name"  =>{"Type"=>"CV","Length"=>200};   //List of keys of p_APIs hash property.
        ,"Status"=>{"Type"=>"N","Length"=>1}};   //1="Active", 2="InactiveRemoved"   
                           ,"Indexes"=>;
        {"name"=>{"Expression"=>"Name"}}};
    ,"public.APIToken"=>{"Fields"=>;
        {"pk"         =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"LinkUID"    =>{"Type"=>"C","Length"=>36};   //Used by UI to edit APIToken. Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"       =>{"Type"=>"CV","Length"=>200};   //Used on List of APIToken.
        ,"Key"        =>{"Type"=>"CV","Length"=>100};   //To be used as a "AccessToken" in REST requests.
        ,"Description"=>{"Type"=>"M","Nullable"=>.t.};   //To describe the use of the API Token. Use Info (Visible to Assigned User).
        ,"AccessMode" =>{"Type"=>"N","Length"=>1};   //1="ProjectAndApplicationSpecific", 2="AllProjectsAndApplicationsReadOnly", 3="AllProjectsAndApplicationsFullAccess"   Used if Type = 1.
        ,"Status"     =>{"Type"=>"N","Length"=>1}};   //1="Active", 2="Inactive"   
                        ,"Indexes"=>;
        {"key"=>{"Expression"=>"Key"}}};
    ,"public.APITokenAccessApplication"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_APIToken"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.APIToken","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Application"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Application","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"AccessLevelDD" =>{"Type"=>"N","Length"=>1}};   //1="None", 2="ReadOnly", 3="UpdateDescriptionandInformationEntries", 4="UpdateDescriptionandInformationEntriesandDiagrams", 5="UpdateAnythingAndImportAndExport", 6="UpdateAnythingAndSyncSchema"   
                                         ,"Indexes"=>;
        {"fk_apitoken"   =>{"Expression"=>"fk_APIToken"};
        ,"fk_application"=>{"Expression"=>"fk_Application"}}};
    ,"public.APITokenAccessProject"=>{"Fields"=>;
        {"pk"           =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"         =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"         =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_APIToken"  =>{"UsedAs"=>"Foreign","ParentTable"=>"public.APIToken","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Project"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Project","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"AccessLevelML"=>{"Type"=>"N","Length"=>1}};   //1="None", 2="ReadOnly", 3="UpdateDescriptionAndInformationEntries", 4="UpdateDescriptionandInformationEntriesAndDiagrams", 5="UpdateAnything"   
                                     ,"Indexes"=>;
        {"fk_apitoken"=>{"Expression"=>"fk_APIToken"};
        ,"fk_project" =>{"Expression"=>"fk_Project"}}};
    ,"public.Application"=>{"Fields"=>;
        {"pk"                                  =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"                                =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"                                =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"LinkCode"                            =>{"Type"=>"CV","Length"=>20};   //Used to create direct link to the Application for data dic management
        ,"Name"                                =>{"Type"=>"CV","Length"=>200};   //12
        ,"UseStatus"                           =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"DocStatus"                           =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Missing", 2="NotNeeded", 3="InProgress", 4="Complete"   
        ,"Description"                         =>{"Type"=>"M","Nullable"=>.t.};
        ,"SupportColumns"                      =>{"Type"=>"M","Nullable"=>.t.};   //List of Column Name that are use as support fields.
        ,"AddForeignKeyIndexORMExport"         =>{"Type"=>"L"};   //Automatically Add Indexes on Integer and Big Integer Foreign Keys during "Export to Harbour_ORM"
        ,"DestructiveDelete"                   =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="None", 2="OnTablesTags", 3="OnNamespaces", 4="EntireApplicationContent", 5="CanDeleteApplication"   
        ,"PublishingUseStatus1"                =>{"Type"=>"L"};   //If should publish to the public elements with Use Status "Unknown". (Upcoming Feature)
        ,"PublishingUseStatus2"                =>{"Type"=>"L"};   //If should publish to the public elements with Use Status "Active". (Upcoming Feature)
        ,"PublishingUseStatus3"                =>{"Type"=>"L"};   //If should publish to the public elements with Use Status "Inactive (Read Only)". (Upcoming Feature)
        ,"PublishingUseStatus4"                =>{"Type"=>"L"};   //If should publish to the public elements with Use Status "Archived". (Upcoming Feature)
        ,"KeyConfig"                           =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Any", 2="Integer", 3="IntegerBig"   
        ,"SetMissingOnDeleteToProtect"         =>{"Type"=>"L","Default"=>"Wharf-False","OnDelete"=>"Protect"};
        ,"TestTableHasPrimaryKey"              =>{"Type"=>"L","Default"=>"Wharf-True"};   //Table must have a Primary Key.
        ,"TestForeignKeyTypeMatchPrimaryKey"   =>{"Type"=>"L","Default"=>"Wharf-True"};   //Foreign Key Type must match Primary Key Type.
        ,"TestForeignKeyIsNullable"            =>{"Type"=>"L","Default"=>"Wharf-True"};   //Foreign Key must be Nullable.
        ,"TestForeignKeyNoDefault"             =>{"Type"=>"L","Default"=>"Wharf-True"};   //Foreign Key may not have a default value.
        ,"TestForeignKeyMissingOnDeleteSetting"=>{"Type"=>"L","Default"=>"Wharf-True"};   //Test missing "On Delete" setting for Foreign Keys.
        ,"TestNumericEnumerationWideEnough"    =>{"Type"=>"L","Default"=>"Wharf-True"};   //Numeric Enumerations must be large enough to handle largest Value.
        ,"TestMaxTableNameLength"              =>{"Type"=>"L","Default"=>"Wharf-True"};   //Maximum Table Name length is 63 characters (Postgres).
        ,"TestMaxColumnNameLength"             =>{"Type"=>"L","Default"=>"Wharf-True"};   //Maximum Column Name length is 59 characters (Postgres).
        ,"TestMaxIndexNameLength"              =>{"Type"=>"L","Default"=>"Wharf-True"};   //Maximum Index Name (After adding Table Names and suffix) 63 characters (Postgresql).
        ,"TestMissingForeignKeyTable"          =>{"Type"=>"L","Default"=>"Wharf-True"};   //All Foreign Keys must point to a table.
        ,"TestMissingEnumerationValues"        =>{"Type"=>"L","Default"=>"Wharf-True"};   //All Enumeration Fields must point to a enumeration.
        ,"TestUseOfDiscontinuedEnumeration"    =>{"Type"=>"L","Default"=>"Wharf-True"};   //Non Discontinued Fields may not point to a Discontinued Enumeration.
        ,"TestUseOfDiscontinuedForeignTable"   =>{"Type"=>"L","Default"=>"Wharf-True"};   //Non Discontinued Foreign Keys may not point to a Discontinued Table.
        ,"TestValidColumnLengthAndScale"       =>{"Type"=>"L","Default"=>"Wharf-True","OnDelete"=>"Protect"}};   //Check validity of columns Length and/or Scale base on column type.
                           ,"Indexes"=>;
        {"linkcode"=>{"Expression"=>"LinkCode"}}};
    ,"public.ApplicationCustomField"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_CustomField"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.CustomField","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Application"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Application","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"Order"         =>{"Type"=>"I"}};   //Display Order.
                                      ,"Indexes"=>;
        {"fk_application"=>{"Expression"=>"fk_Application"};
        ,"fk_customfield"=>{"Expression"=>"fk_CustomField"}}};
    ,"public.Association"=>{"Fields"=>;
        {"pk"               =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"             =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"             =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Model"         =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Model","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_Package"       =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Package","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"LinkUID"          =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"             =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Display in the middle of the association representation.
        ,"NumberOfEndpoints"=>{"Type"=>"N","Length"=>2};   //Must more than 1 and less than 99. This will assist in visualization.
        ,"Description"      =>{"Type"=>"M","Nullable"=>.t.};   //Meaning of the association. Display when clicking on the association.
        ,"UseStatus"        =>{"Type"=>"N","Length"=>1,"Default"=>"1"}};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
                           ,"Indexes"=>;
        {"fk_model"  =>{"Expression"=>"fk_Model"};
        ,"fk_package"=>{"Expression"=>"fk_Package"}}};
    ,"public.AssociationTableMapping"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Association"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Association","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_Table"      =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Table","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"}};   //Text representation of the value.
                                       ,"Indexes"=>;
        {"fk_association"=>{"Expression"=>"fk_Association"};
        ,"fk_table"      =>{"Expression"=>"fk_Table"}}};
    ,"public.Attribute"=>{"Fields"=>;
        {"pk"                 =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"               =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"               =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Entity"          =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Entity","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_DataType"        =>{"UsedAs"=>"Foreign","ParentTable"=>"public.DataType","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_Attribute"       =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Attribute","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};   //To provide tree-like structure.
        ,"fk_ModelEnumeration"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.ModelEnumeration","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"LinkUID"            =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"               =>{"Type"=>"CV","Length"=>200};
        ,"BoundLower"         =>{"Type"=>"CV","Length"=>4,"Nullable"=>.t.};
        ,"BoundUpper"         =>{"Type"=>"CV","Length"=>4,"Nullable"=>.t.};
        ,"Description"        =>{"Type"=>"M","Nullable"=>.t.};
        ,"IsObject"           =>{"Type"=>"L"};   //It is an nested attribute.
        ,"UseStatus"          =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"FullName"           =>{"Type"=>"M"};   //Denormalized sum of all the parent name. Unique in Entity.
        ,"FullPk"             =>{"Type"=>"M"};   //Denormalized sum of all the pk fields separated by '*'.
        ,"TreeLevel"          =>{"Type"=>"I"};   //Denormalized Tree dept. Can be used to assist indentation on display.Unique in Entity.
        ,"TreeOrder1"         =>{"Type"=>"I"}};   //Order full list. Unique in Entity. (NOT Denormalized but actually used and fixed as needed.).
                         ,"Indexes"=>;
        {"fk_attribute"       =>{"Expression"=>"fk_Attribute"};
        ,"fk_datatype"        =>{"Expression"=>"fk_DataType"};
        ,"fk_entity"          =>{"Expression"=>"fk_Entity"};
        ,"fk_modelenumeration"=>{"Expression"=>"fk_ModelEnumeration"}}};
    ,"public.AttributeColumnMapping"=>{"Fields"=>;
        {"pk"          =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"        =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"        =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Attribute"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Attribute","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_Column"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Column","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"}};   //Text representation of the value.
                                      ,"Indexes"=>;
        {"fk_attribute"=>{"Expression"=>"fk_Attribute"};
        ,"fk_column"   =>{"Expression"=>"fk_Column"}}};
    ,"public.Column"=>{"Fields"=>;
        {"pk"                =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Table"          =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Table","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_TableForeign"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Table","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};   //Parent Table if this is a foreign key.
        ,"fk_Enumeration"    =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Enumeration","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"Order"             =>{"Type"=>"I"};   //Display order only. Is not used to enforce column position in tables.
        ,"Name"              =>{"Type"=>"CV","Length"=>200};
        ,"AKA"               =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Also Known As. Will be displayed in Diagrams, not used in physical implementation.
        ,"UsedAs"            =>{"Type"=>"N","Length"=>1};   //1="Regular", 2="PrimaryKey", 3="ForeignKey", 4="Support"   
        ,"UsedBy"            =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="AllServers", 2="MySQLOnly", 3="PostgreSQLOnly"   To restrict the existence of the column to a particular type of backend server.
        ,"UseStatus"         =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"DocStatus"         =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Missing", 2="NotNeeded", 3="InProgress", 4="Complete"   
        ,"Type"              =>{"Type"=>"C","Length"=>3};
        ,"Array"             =>{"Type"=>"L"};   //Currently only useful when using PostgreSQL backends. Specifies if the column should be an array of "Type" content.
        ,"Length"            =>{"Type"=>"I","Nullable"=>.t.};
        ,"Scale"             =>{"Type"=>"I","Nullable"=>.t.};
        ,"Nullable"          =>{"Type"=>"L"};
        ,"DefaultType"       =>{"Type"=>"N","Length"=>2};   //0="NotSet", 1="Custom", 10="Today", 11="Now", 12="RandomUuid", 13="False", 14="True", 15="AutoIncrement"   Either "DefaultCustom" or "DefaultType" can be used.
        ,"DefaultCustom"     =>{"Type"=>"M","Nullable"=>.t.};   //Text version of the default value/expression. Either "DefaultCustom" or "DefaultType" can be used.
        ,"ForeignKeyUse"     =>{"Type"=>"CV","Length"=>120,"Nullable"=>.t.};   //Short Description used during Visualization.
        ,"ForeignKeyOptional"=>{"Type"=>"L"};
        ,"OnDelete"          =>{"Type"=>"N","Length"=>1,"Default"=>"0"};   //1="NotSet", 2="Protect", 3="Cascade", 4="BreakLink"   Use on Foreign Keys, referential integrity rule to be applied when related parent record is deleted.
        ,"Unicode"           =>{"Type"=>"L"};   //Only Applicable to Character types.
        ,"Description"       =>{"Type"=>"M","Nullable"=>.t.};
        ,"TestWarning"       =>{"Type"=>"M","Nullable"=>.t.};   //Last Test Run warning messages.
        ,"LastNativeType"    =>{"Type"=>"M","Nullable"=>.t.}};   //Set during the last "Load Schema". This is the native column type provided by the backend server.
                      ,"Indexes"=>;
        {"fk_enumeration" =>{"Expression"=>"fk_Enumeration"};
        ,"fk_table"       =>{"Expression"=>"fk_Table"};
        ,"fk_tableforeign"=>{"Expression"=>"fk_TableForeign"}}};
    ,"public.ColumnMapping"=>{"Fields"=>;
        {"pk"           =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"         =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"         =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_ColumnFrom"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Column","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_ColumnTo"  =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Column","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"Description"  =>{"Type"=>"M","Nullable"=>.t.}};   //Text representation of the value.
                             ,"Indexes"=>;
        {"fk_columnfrom"=>{"Expression"=>"fk_ColumnFrom"};
        ,"fk_columnto"  =>{"Expression"=>"fk_ColumnTo"}}};
    ,"public.CustomField"=>{"Fields"=>;
        {"pk"              =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"            =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"            =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"Code"            =>{"Type"=>"CV","Length"=>10};
        ,"Name"            =>{"Type"=>"CV","Length"=>200};   //Must be unique.
        ,"Label"           =>{"Type"=>"CV","Length"=>200};   //Used on Entry screen. Can be the same as long as UsedOn is different or Status is 3.
        ,"Type"            =>{"Type"=>"N","Length"=>1};   //1="Logical", 2="MultiChoice", 3="String", 4="TextArea", 5="Date"   
        ,"OptionDefinition"=>{"Type"=>"M","Nullable"=>.t.};   //Used if Type = 2. Row of integer / labels.
        ,"Length"          =>{"Type"=>"N","Length"=>4,"Nullable"=>.t.};   //Used if Type = 3.
        ,"Width"           =>{"Type"=>"N","Length"=>3,"Nullable"=>.t.};   //Used if Type = 4. Width in Characters.
        ,"Height"          =>{"Type"=>"N","Length"=>3,"Nullable"=>.t.};   //Used if Type = 4. Number of Rows.
        ,"Description"     =>{"Type"=>"M","Nullable"=>.t.};
        ,"UsedOn"          =>{"Type"=>"N","Length"=>2};   //1="Application", 2="Namespace", 3="Table", 4="Column", 5="Model", 6="Entity", 7="Association", 8="Package", 9="DataType", 10="Attribute"   
        ,"Status"          =>{"Type"=>"N","Length"=>1}};   //1="Active", 2="Inactive", 3="Hidden"   
                           };
    ,"public.CustomFieldValue"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_CustomField"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.CustomField","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Entity"     =>{"Type"=>"I","Nullable"=>.t.};   //Foreign key to "table", "column", ... depending of the type of custom field, see value in public.CustomField.UsedOn. MAY NOT BE FLAGGED AS FOREIGN KEY since does not have a single parent table.
        ,"ValueI"        =>{"Type"=>"I","Nullable"=>.t.};   //Used if public.CustomField.Type = 2.
        ,"ValueM"        =>{"Type"=>"M","Nullable"=>.t.};   //Used if public.CustomField.Type = 3 or 4.
        ,"ValueD"        =>{"Type"=>"D","Nullable"=>.t.}};   //Used if public.CustomField.Type = 5.
                                ,"Indexes"=>;
        {"fk_customfield"=>{"Expression"=>"fk_CustomField"};
        ,"fk_entity"     =>{"Expression"=>"fk_Entity"}}};
    ,"public.DataType"=>{"Fields"=>;
        {"pk"              =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"            =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"            =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_DataType"     =>{"UsedAs"=>"Foreign","ParentTable"=>"public.DataType","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_Model"        =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Model","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_PrimitiveType"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.PrimitiveType","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"LinkUID"         =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"            =>{"Type"=>"CV","Length"=>200};
        ,"Description"     =>{"Type"=>"M","Nullable"=>.t.};
        ,"UseStatus"       =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"FullName"        =>{"Type"=>"M"};   //Denormalized sum of all the parent name. Unique in Model.
        ,"FullPk"          =>{"Type"=>"M"};   //Denormalized sum of all the pk fields separated by '*'.
        ,"TreeLevel"       =>{"Type"=>"I"};   //Denormalized Tree dept. Can be used to assist indentation on display.Unique in Model.
        ,"TreeOrder1"      =>{"Type"=>"I"}};   //Denormalized used to order full list. Unique in Model.
                        ,"Indexes"=>;
        {"fk_datatype"     =>{"Expression"=>"fk_DataType"};
        ,"fk_model"        =>{"Expression"=>"fk_Model"};
        ,"fk_primitivetype"=>{"Expression"=>"fk_PrimitiveType"}}};
    ,"public.Deployment"=>{"Fields"=>;
        {"pk"                =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Application"    =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Application","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"LinkUID"           =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"              =>{"Type"=>"CV","Length"=>200};
        ,"Description"       =>{"Type"=>"M","Nullable"=>.t.};
        ,"Status"            =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Active", 2="OnHold"   
        ,"BackendType"       =>{"Type"=>"N","Length"=>1,"Nullable"=>.t.};   //1="MariaDB", 2="MySQL", 3="PostgreSQL", 4="MSSQL"   Connection Info Backend Type.
        ,"Server"            =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Connection Info Server/Host URL/IP.
        ,"Port"              =>{"Type"=>"I","Nullable"=>.t.};   //Connection Info Port if not default one for Backend Type.
        ,"User"              =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Connection Info User Account to use to connect.
        ,"Database"          =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Connection Info Database to connect to.
        ,"Namespaces"        =>{"Type"=>"CV","Length"=>400,"Nullable"=>.t.};   //Connection Info If blank all Namespaces (PostgreSQL schemas) will be loaded, otherwise list the schema names separated with ",".
        ,"PasswordStorage"   =>{"Type"=>"N","Length"=>1,"Nullable"=>.t.};   //1="Encrypted", 2="InConfigTxt", 3="InEnvironmentVariable", 4="UserIsAWSIAMAccount"   Connection Info  Method to store/retrieve password.
        ,"PasswordCrypt"     =>{"Type"=>"R","Nullable"=>.t.};   //Used if PasswordStorage = 1.
        ,"PasswordConfigKey" =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Used if PasswordStorage = 2. Key Name in config.txt.
        ,"PasswordEnvVarName"=>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Used if PasswordStorage = 3. Name of Environment Variable to use to retrieve password.
        ,"SetForeignKey"     =>{"Type"=>"N","Length"=>1,"Nullable"=>.t.};   //1="Not", 2="ForeignKeyRestrictions", 3="Onp_TableName", 4="Onfk_TableName", 5="OnTableName_id"   Connection Info to detect foreign keys.
        ,"AllowUpdates"      =>{"Type"=>"L","Default"=>"Wharf-False","OnDelete"=>"Protect"}};   //If the "Update" option can be executed under the "Deployment Tools".
                          ,"Indexes"=>;
        {"fk_application"=>{"Expression"=>"fk_Application"}}};
    ,"public.Diagram"=>{"Fields"=>;
        {"pk"                 =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"               =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"               =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Application"     =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Application","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"LinkUID"            =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"               =>{"Type"=>"CV","Length"=>200};
        ,"UseStatus"          =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"DocStatus"          =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Missing", 2="NotNeeded", 3="InProgress", 4="Complete"   
        ,"Description"        =>{"Type"=>"M","Nullable"=>.t.};
        ,"NodeDisplayMode"    =>{"Type"=>"N","Length"=>1};   //1="TableNameAndAlias", 2="TableAliasOrName", 3="TableName"   
        ,"NodeShowDescription"=>{"Type"=>"L"};   //True If the table description should be included in the node.
        ,"NodeMinHeight"      =>{"Type"=>"I"};
        ,"NodeMaxWidth"       =>{"Type"=>"I"};
        ,"RenderMode"         =>{"Type"=>"N","Length"=>1};   //1="VisJs", 2="mxgraph"   The behavior provided to users for manipulating diagrams will depend on the JavaScript library used.
        ,"VisPos"             =>{"Type"=>"M","Nullable"=>.t.};   //Last Visualization Positions for VisJs mode.
        ,"MxgPos"             =>{"Type"=>"M","Nullable"=>.t.}};   //The layout of all tables and relationship, in JSon format for mxgraph mode.
                       ,"Indexes"=>;
        {"fk_application"=>{"Expression"=>"fk_Application"}}};
    ,"public.DiagramEntity"=>{"Fields"=>;
        {"pk"                =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Entity"         =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Entity","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_ModelingDiagram"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.ModelingDiagram","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"}};
                             ,"Indexes"=>;
        {"fk_entity"         =>{"Expression"=>"fk_Entity"};
        ,"fk_modelingdiagram"=>{"Expression"=>"fk_ModelingDiagram"}}};
    ,"public.DiagramTable"=>{"Fields"=>;
        {"pk"        =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"      =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"      =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Diagram"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Diagram","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Table"  =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Table","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"}};
                            ,"Indexes"=>;
        {"fk_diagram"=>{"Expression"=>"fk_Diagram"};
        ,"fk_table"  =>{"Expression"=>"fk_Table"}}};
    ,"public.Endpoint"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Entity"     =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Entity","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_Association"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Association","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"Name"          =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Showing near the entity in a representation.
        ,"BoundLower"    =>{"Type"=>"CV","Length"=>4,"Nullable"=>.t.};
        ,"BoundUpper"    =>{"Type"=>"CV","Length"=>4,"Nullable"=>.t.};
        ,"IsContainment" =>{"Type"=>"L"};   //If should show a diamond.
        ,"Description"   =>{"Type"=>"M","Nullable"=>.t.}};   //Not certain if needed.
                        ,"Indexes"=>;
        {"fk_association"=>{"Expression"=>"fk_Association"};
        ,"fk_entity"     =>{"Expression"=>"fk_Entity"}}};
    ,"public.Entity"=>{"Fields"=>;
        {"pk"         =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Package" =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Package","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_Model"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Model","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"LinkUID"    =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"       =>{"Type"=>"CV","Length"=>200};
        ,"Description"=>{"Type"=>"M","Nullable"=>.t.};   //AKA Definition.
        ,"Information"=>{"Type"=>"M","Nullable"=>.t.};   //Should support mark down (md).
        ,"UseStatus"  =>{"Type"=>"N","Length"=>1,"Default"=>"1"}};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
                      ,"Indexes"=>;
        {"fk_model"  =>{"Expression"=>"fk_Model"};
        ,"fk_package"=>{"Expression"=>"fk_Package"}}};
    ,"public.EntityTableMapping"=>{"Fields"=>;
        {"pk"       =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"     =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"     =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Entity"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Entity","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_Table" =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Table","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"}};   //Text representation of the value.
                                  ,"Indexes"=>;
        {"fk_entity"=>{"Expression"=>"fk_Entity"};
        ,"fk_table" =>{"Expression"=>"fk_Table"}}};
    ,"public.Enumeration"=>{"Fields"=>;
        {"pk"             =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"           =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"           =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Namespace"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Namespace","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"Name"           =>{"Type"=>"CV","Length"=>200};
        ,"AKA"            =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Also Known As. Not used in physical implementation.
        ,"ImplementAs"    =>{"Type"=>"N","Length"=>1};   //1="NativeSQLEnum", 2="Integer", 3="Numeric", 4="VarChar"   Besides PostgreSQL native support to enums, it is possible to make integer, numeric and string fields behave as enumerations.
        ,"ImplementLength"=>{"Type"=>"I","Nullable"=>.t.};   //Used if ImplementAs is 3 or 4.
        ,"Description"    =>{"Type"=>"M","Nullable"=>.t.};
        ,"UseStatus"      =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"DocStatus"      =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Missing", 2="NotNeeded", 3="InProgress", 4="Complete"   
        ,"TestWarning"    =>{"Type"=>"M","Nullable"=>.t.}};   //Last Test Run warning messages.
                           ,"Indexes"=>;
        {"fk_namespace"=>{"Expression"=>"fk_Namespace"}}};
    ,"public.EnumValue"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Enumeration"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Enumeration","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"Number"        =>{"Type"=>"I","Nullable"=>.t.};   //Optional. If the enum is not implemented as a Enum SQL type, but more as a pseudo value.
        ,"Order"         =>{"Type"=>"I"};   //Display Order
        ,"Name"          =>{"Type"=>"CV","Length"=>200};
        ,"AKA"           =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Used for display only, not in physical implementation.
        ,"Description"   =>{"Type"=>"M","Nullable"=>.t.};
        ,"UseStatus"     =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"DocStatus"     =>{"Type"=>"N","Length"=>1,"Default"=>"1"}};   //1="Missing", 2="NotNeeded", 3="InProgress", 4="Complete"   
                         ,"Indexes"=>;
        {"fk_enumeration"=>{"Expression"=>"fk_Enumeration"}}};
    ,"public.FastCGIRunLog"=>{"Fields"=>;
        {"pk"                =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"dati"              =>{"Type"=>"DT"};   //First Request time.
        ,"RequestCount"      =>{"Type"=>"I"};
        ,"ErrorInfo"         =>{"Type"=>"M","Nullable"=>.t.};   //Error Info on Crash.
        ,"ApplicationVersion"=>{"Type"=>"CV","Length"=>100};
        ,"IP"                =>{"Type"=>"CV","Length"=>36};   //In case using IP6.
        ,"OSInfo"            =>{"Type"=>"M","Nullable"=>.t.};
        ,"HostInfo"          =>{"Type"=>"M","Nullable"=>.t.}};
                             };
    ,"public.Index"=>{"Fields"=>;
        {"pk"         =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Table"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Table","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"Name"       =>{"Type"=>"CV","Length"=>200};
        ,"Unique"     =>{"Type"=>"L"};
        ,"Expression" =>{"Type"=>"M","Nullable"=>.t.};
        ,"Description"=>{"Type"=>"M","Nullable"=>.t.};
        ,"Algo"       =>{"Type"=>"N","Length"=>1};   //1="BTREE"   
        ,"UsedBy"     =>{"Type"=>"N","Length"=>1};   //1="AllServers", 2="MySQLOnly", 3="PostgreSQLOnly"   
        ,"UseStatus"  =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"DocStatus"  =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Missing", 2="NotNeeded", 3="InProgress", 4="Complete"   
        ,"TestWarning"=>{"Type"=>"M","Nullable"=>.t.}};   //Last Test Run warning messages.
                     ,"Indexes"=>;
        {"fk_table"=>{"Expression"=>"fk_Table"}}};
    ,"public.IndexColumn"=>{"Fields"=>;
        {"pk"       =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"     =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"     =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Index" =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Index","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Column"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Column","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"}};
                           ,"Indexes"=>;
        {"fk_column"=>{"Expression"=>"fk_Column"};
        ,"fk_index" =>{"Expression"=>"fk_Index"}}};
    ,"public.LinkedEntity"=>{"Fields"=>;
        {"pk"         =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"LinkUID"    =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Description"=>{"Type"=>"M","Nullable"=>.t.};
        ,"fk_Entity1" =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Entity","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};   //From / To
        ,"fk_Entity2" =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Entity","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"}};   //From / To
                            ,"Indexes"=>;
        {"fk_entity1"=>{"Expression"=>"fk_Entity1"};
        ,"fk_entity2"=>{"Expression"=>"fk_Entity2"}}};
    ,"public.LinkedModel"=>{"Fields"=>;
        {"pk"       =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"     =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"     =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Model1"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Model","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};   //From / To
        ,"fk_Model2"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Model","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"}};   //From / To
                           ,"Indexes"=>;
        {"fk_model1"=>{"Expression"=>"fk_Model1"};
        ,"fk_model2"=>{"Expression"=>"fk_Model2"}}};
    ,"public.LoginLogs"=>{"Fields"=>;
        {"pk"       =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"     =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"     =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_User"  =>{"UsedAs"=>"Foreign","ParentTable"=>"public.User","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"TimeIn"   =>{"Type"=>"DT","Scale"=>2};
        ,"TimeOut"  =>{"Type"=>"DT","Scale"=>2,"Nullable"=>.t.};
        ,"IP"       =>{"Type"=>"CV","Length"=>45};
        ,"Signature"=>{"Type"=>"CV","Length"=>50};   //A Random string used as a session token. Used to verify who is logged in.
        ,"Attempts" =>{"Type"=>"I"};   //Counter on the number of attempts to login.
        ,"Status"   =>{"Type"=>"N","Length"=>1}};   //1="LoggedIn", 2="UserLogout", 3="ImplicitLogout"   
                         ,"Indexes"=>;
        {"fk_user"=>{"Expression"=>"fk_User"}}};
    ,"public.Model"=>{"Fields"=>;
        {"pk"         =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Project" =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Project","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"LinkUID"    =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"       =>{"Type"=>"CV","Length"=>100};   //Unique in application.
        ,"Description"=>{"Type"=>"M","Nullable"=>.t.};
        ,"Stage"      =>{"Type"=>"N","Length"=>1}};   //1="Proposed", 2="Draft", 3="Beta", 4="Stable", 5="InUse", 6="Discontinued"   
                     ,"Indexes"=>;
        {"fk_project"=>{"Expression"=>"fk_Project"}}};
    ,"public.ModelEnumeration"=>{"Fields"=>;
        {"pk"         =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Model"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Model","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"LinkUID"    =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"       =>{"Type"=>"CV","Length"=>200};
        ,"Description"=>{"Type"=>"M","Nullable"=>.t.};
        ,"UseStatus"  =>{"Type"=>"N","Length"=>1,"Default"=>"1"}};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
                                ,"Indexes"=>;
        {"fk_model"=>{"Expression"=>"fk_Model"}}};
    ,"public.ModelEnumValue"=>{"Fields"=>;
        {"pk"                 =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"               =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"               =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_ModelEnumeration"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.ModelEnumeration","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"Number"             =>{"Type"=>"I","Nullable"=>.t.};   //Optional. If the enum is not implemented as a Enum SQL type, but more as a pseudo value.
        ,"Order"              =>{"Type"=>"I"};   //Display Order.
        ,"Name"               =>{"Type"=>"CV","Length"=>200};
        ,"Description"        =>{"Type"=>"M","Nullable"=>.t.}};
                              ,"Indexes"=>;
        {"fk_modelenumeration"=>{"Expression"=>"fk_ModelEnumeration"}}};
    ,"public.ModelingDiagram"=>{"Fields"=>;
        {"pk"                    =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"                  =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"                  =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Model"              =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Model","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"Name"                  =>{"Type"=>"CV","Length"=>200};
        ,"LinkUID"               =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"NodeShowDescription"   =>{"Type"=>"L"};   //True If the node description should be included.
        ,"VisPos"                =>{"Type"=>"M","Nullable"=>.t.};   //Last Visualization Positions.
        ,"NodeMinHeight"         =>{"Type"=>"I"};
        ,"NodeMaxWidth"          =>{"Type"=>"I"};
        ,"AssociationShowName"   =>{"Type"=>"L"};   //True If the association name should be shown.
        ,"AssociationEndShowName"=>{"Type"=>"L"};   //True If the association end name should be shown.
        ,"UseStatus"             =>{"Type"=>"N","Length"=>1,"Default"=>"1"}};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
                               ,"Indexes"=>;
        {"fk_model"=>{"Expression"=>"fk_Model"}}};
    ,"public.Namespace"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Application"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Application","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"Name"          =>{"Type"=>"CV","Length"=>200};
        ,"AKA"           =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Used for display only, not in physical implementation.
        ,"UseStatus"     =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"DocStatus"     =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Missing", 2="NotNeeded", 3="InProgress", 4="Complete"   
        ,"Description"   =>{"Type"=>"M","Nullable"=>.t.}};
                         ,"Indexes"=>;
        {"fk_application"=>{"Expression"=>"fk_Application"}}};
    ,"public.Package"=>{"Fields"=>;
        {"pk"        =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"      =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"      =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Package"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Package","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"fk_Model"  =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Model","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"LinkUID"   =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"      =>{"Type"=>"CV","Length"=>200};
        ,"UseStatus" =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"FullName"  =>{"Type"=>"M"};   //Denormalized sum of all the parent name. Unique in Model.
        ,"FullPk"    =>{"Type"=>"M"};   //Denormalized sum of all the pk fields separated by '*'.
        ,"TreeLevel" =>{"Type"=>"I"};   //Denormalized Tree dept. Can be used to assist indentation on display.Unique in Model.
        ,"TreeOrder1"=>{"Type"=>"I"}};   //Denormalized used to order full list. Unique in Model.
                       ,"Indexes"=>;
        {"fk_model"  =>{"Expression"=>"fk_Model"};
        ,"fk_package"=>{"Expression"=>"fk_Package"}}};
    ,"public.PrimitiveType"=>{"Fields"=>;
        {"pk"         =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Project" =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Project","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"LinkUID"    =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"       =>{"Type"=>"CV","Length"=>200};
        ,"Description"=>{"Type"=>"M","Nullable"=>.t.}};
                             ,"Indexes"=>;
        {"fk_project"=>{"Expression"=>"fk_Project"}}};
    ,"public.Project"=>{"Fields"=>;
        {"pk"                            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"                          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"                          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"LinkUID"                       =>{"Type"=>"C","Length"=>36};   //Used to create direct link, Is a UUID generated by calling postgresql "select gen_random_uuid()".
        ,"Name"                          =>{"Type"=>"CV","Length"=>200};
        ,"UseStatus"                     =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"Description"                   =>{"Type"=>"M","Nullable"=>.t.};
        ,"AlternateNameForModel"         =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of Model.
        ,"AlternateNameForModels"        =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of Models.
        ,"AlternateNameForEntity"        =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of Entity.
        ,"AlternateNameForEntities"      =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of Entities.
        ,"AlternateNameForAssociation"   =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of Association.
        ,"AlternateNameForAssociations"  =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of Associations.
        ,"AlternateNameForAttribute"     =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of Attribute.
        ,"AlternateNameForAttributes"    =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of Attributes.
        ,"AlternateNameForDataType"      =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of DataType.
        ,"AlternateNameForDataTypes"     =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of DataTypes.
        ,"AlternateNameForPackage"       =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of Package.
        ,"AlternateNameForPackages"      =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of Packages.
        ,"AlternateNameForLinkedEntity"  =>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of LinkedEntity.
        ,"AlternateNameForLinkedEntities"=>{"Type"=>"CV","Length"=>80,"Nullable"=>.t.};   //Renaming of LinkedEntities.
        ,"ValidEndpointBoundLowerValues" =>{"Type"=>"M","Nullable"=>.t.};   //Association Endpoint List of Valid Bound Lower.
        ,"ValidEndpointBoundUpperValues" =>{"Type"=>"M","Nullable"=>.t.};   //Association Endpoint List of Valid Bound Upper.
        ,"DestructiveDelete"             =>{"Type"=>"N","Length"=>1,"Default"=>"1"}};   //1="None", 2="OnEntitiesAssociations", 3="CanDeleteModels"   
                       };
    ,"public.ProjectCustomField"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_CustomField"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.CustomField","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Project"    =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Project","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"Order"         =>{"Type"=>"I"}};   //Display Order.
                                  ,"Indexes"=>;
        {"fk_customfield"=>{"Expression"=>"fk_CustomField"};
        ,"fk_project"    =>{"Expression"=>"fk_Project"}}};
    ,"public.Table"=>{"Fields"=>;
        {"pk"          =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"        =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"        =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Namespace"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Namespace","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"Name"        =>{"Type"=>"CV","Length"=>200};
        ,"AKA"         =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Used for display only, not in physical implementation.
        ,"UseStatus"   =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"DocStatus"   =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Missing", 2="NotNeeded", 3="InProgress", 4="Complete"   
        ,"Description" =>{"Type"=>"M","Nullable"=>.t.};
        ,"Information" =>{"Type"=>"M","Nullable"=>.t.};   //Any engineering notes. Will accept md (Mark Down).
        ,"Unlogged"    =>{"Type"=>"L"};   //Used for PostgreSQL. Data written to unlogged tables is not written to the write-ahead log, and no replication occurs.
        ,"TestWarning" =>{"Type"=>"M","Nullable"=>.t.}};   //Last Test Run warning messages.
                     ,"Indexes"=>;
        {"fk_namespace"=>{"Expression"=>"fk_Namespace"}}};
    ,"public.TableMapping"=>{"Fields"=>;
        {"pk"          =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"        =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"        =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_TableFrom"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Table","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_TableTo"  =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Table","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"Description" =>{"Type"=>"M"}};   //Text representation of the value.
                            ,"Indexes"=>;
        {"fk_tablefrom"=>{"Expression"=>"fk_TableFrom"};
        ,"fk_tableto"  =>{"Expression"=>"fk_TableTo"}}};
    ,"public.Tag"=>{"Fields"=>;
        {"pk"             =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"           =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"           =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Application" =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Application","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"Code"           =>{"Type"=>"CV","Length"=>10};
        ,"Name"           =>{"Type"=>"CV","Length"=>100};
        ,"TableUseStatus" =>{"Type"=>"N","Length"=>1};   //1="DoNotUse", 2="Active", 3="Discontinued"   
        ,"ColumnUseStatus"=>{"Type"=>"N","Length"=>1};   //1="DoNotUse", 2="Active", 3="Discontinued"   
        ,"Description"    =>{"Type"=>"M","Nullable"=>.t.}};
                   ,"Indexes"=>;
        {"fk_application"=>{"Expression"=>"fk_Application"}}};
    ,"public.TagColumn"=>{"Fields"=>;
        {"pk"       =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"     =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"     =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Tag"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Tag","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Column"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Column","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"}};
                         ,"Indexes"=>;
        {"fk_column"=>{"Expression"=>"fk_Column"};
        ,"fk_tag"   =>{"Expression"=>"fk_Tag"}}};
    ,"public.TagTable"=>{"Fields"=>;
        {"pk"      =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"    =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"    =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Tag"  =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Tag","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Table"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Table","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"}};
                        ,"Indexes"=>;
        {"fk_table"=>{"Expression"=>"fk_Table"};
        ,"fk_tag"  =>{"Expression"=>"fk_Tag"}}};
    ,"public.TemplateColumn"=>{"Fields"=>;
        {"pk"              =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"            =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"            =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_TemplateTable"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.TemplateTable","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"Order"           =>{"Type"=>"I"};   //Display Order.
        ,"Name"            =>{"Type"=>"CV","Length"=>200};
        ,"AKA"             =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Used for display only, not in physical implementation.
        ,"UsedAs"          =>{"Type"=>"N","Length"=>1};   //1="Regular", 2="PrimaryKey", 3="ForeignKey", 4="Support"   
        ,"UsedBy"          =>{"Type"=>"N","Length"=>1};   //1="AllServers", 2="MySQLOnly", 3="PostgreSQLOnly"   
        ,"UseStatus"       =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Unknown", 2="Proposed", 3="UnderDevelopment", 4="Active", 5="ToBeDiscontinued", 6="Discontinued"   
        ,"DocStatus"       =>{"Type"=>"N","Length"=>1,"Default"=>"1"};   //1="Missing", 2="NotNeeded", 3="InProgress", 4="Complete"   
        ,"Type"            =>{"Type"=>"C","Length"=>3};   //Unlike Column table no support to enumerations, since those are Namespace specific.
        ,"Array"           =>{"Type"=>"L"};   //Used for PostgreSQL only. Fields can be of an array of types.
        ,"Length"          =>{"Type"=>"I","Nullable"=>.t.};
        ,"Scale"           =>{"Type"=>"I","Nullable"=>.t.};
        ,"Nullable"        =>{"Type"=>"L"};
        ,"DefaultType"     =>{"Type"=>"N","Length"=>2};   //0="NotSet", 1="Custom", 10="Today", 11="Now", 12="RandomUuid", 13="False", 14="True", 15="AutoIncrement"   Either "DefaultCustom" or "DefaultType" can be used.
        ,"DefaultCustom"   =>{"Type"=>"M","Nullable"=>.t.};   //Text version of the default value/expression. Either "DefaultCustom" or "DefaultType" can be used.
        ,"Unicode"         =>{"Type"=>"L"};   //Only Applicable to Character types.
        ,"Description"     =>{"Type"=>"M","Nullable"=>.t.}};
                              ,"Indexes"=>;
        {"fk_templatetable"=>{"Expression"=>"fk_TemplateTable"}}};
    ,"public.TemplateTable"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_Application"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Application","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Protect"};
        ,"Name"          =>{"Type"=>"CV","Length"=>200}};
                             ,"Indexes"=>;
        {"fk_application"=>{"Expression"=>"fk_Application"}}};
    ,"public.User"=>{"Fields"=>;
        {"pk"         =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"       =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"FirstName"  =>{"Type"=>"CV","Length"=>200};
        ,"LastName"   =>{"Type"=>"CV","Length"=>200};
        ,"id"         =>{"Type"=>"CV","Length"=>100};
        ,"Password"   =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Allow Null so to set a password to default.
        ,"AccessMode" =>{"Type"=>"N","Length"=>1};   //1="ProjectAndApplicationSpecific", 2="AllProjectsAndApplicationsReadOnly", 3="AllProjectsAndApplicationsFullAccess", 4="RootAdmin"   
        ,"Status"     =>{"Type"=>"N","Length"=>1};   //1="Active", 2="Inactive"   
        ,"Description"=>{"Type"=>"M","Nullable"=>.t.}};
                    };
    ,"public.UserAccessApplication"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_User"       =>{"UsedAs"=>"Foreign","ParentTable"=>"public.User","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Application"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Application","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"AccessLevelDD" =>{"Type"=>"N","Length"=>1}};   //1="None", 2="ReadOnly", 3="EditDescriptionAndInformationEntries", 4="EditDescriptionAndInformationEntriesAndDiagrams", 5="EditAnythingAndImportExport", 6="EditAnythingAndSyncSchema", 7="FullAccess"   Data Dictionary Access Level for User in Application.
                                     ,"Indexes"=>;
        {"fk_application"=>{"Expression"=>"fk_Application"};
        ,"fk_user"       =>{"Expression"=>"fk_User"}}};
    ,"public.UserAccessProject"=>{"Fields"=>;
        {"pk"           =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"         =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"         =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_User"      =>{"UsedAs"=>"Foreign","ParentTable"=>"public.User","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Project"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Project","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"AccessLevelML"=>{"Type"=>"N","Length"=>1}};   //1="None", 2="ReadOnly", 3="EditDescriptionAndInformationEntries", 4="EditDescriptionAndInformationEntriesAndDiagrams", 5="EditAnything", 7="FullAccess"   
                                 ,"Indexes"=>;
        {"fk_project"=>{"Expression"=>"fk_Project"};
        ,"fk_user"   =>{"Expression"=>"fk_User"}}};
    ,"public.UserSetting"=>{"Fields"=>;
        {"pk"                =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_User"           =>{"UsedAs"=>"Foreign","ParentTable"=>"public.User","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Diagram"        =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Diagram","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};   //Used only if setting is specific to a particular Application Diagram.
        ,"fk_ModelingDiagram"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.ModelingDiagram","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};   //Used only if setting is specific to a particular Modeling Diagram.
        ,"KeyC"              =>{"Type"=>"CV","Length"=>100};   //Any Text that will be know in the app.
        ,"ValueC"            =>{"Type"=>"M"};   //Text representation of the value.
        ,"ValueType"         =>{"Type"=>"N","Length"=>1,"Default"=>"1"}};   //1="String", 2="Integer", 3="Date", 4="BlobMemo"   
                           ,"Indexes"=>;
        {"fk_diagram"        =>{"Expression"=>"fk_Diagram"};
        ,"fk_modelingdiagram"=>{"Expression"=>"fk_ModelingDiagram"};
        ,"fk_user"           =>{"Expression"=>"fk_User"};
        ,"keyc"              =>{"Expression"=>"KeyC"}}};
    ,"public.UserSettingApplication"=>{"Fields"=>;
        {"pk"               =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"             =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"             =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_User"          =>{"UsedAs"=>"Foreign","ParentTable"=>"public.User","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Application"   =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Application","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Diagram"       =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Diagram","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};   //Last Diagram used by the user while in an application.
        ,"fk_Deployment"    =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Deployment","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};   //Last Deployment used by the user while in an application.
        ,"SyncBackendType"  =>{"Type"=>"N","Length"=>1,"Nullable"=>.t.};   //1="MariaDB", 2="MySQL", 3="PostgreSQL", 4="MSSQL"   Last Sync setting used by the user while in an application. Backend Type.
        ,"SyncServer"       =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Last Sync setting used by the user while in an application. Server/Host URL/IP.
        ,"SyncPort"         =>{"Type"=>"I","Nullable"=>.t.};   //Last Sync setting used by the user while in an application. Port if not default one for Backend Type.
        ,"SyncUser"         =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Last Sync setting used by the user while in an application. User Account to use to connect.
        ,"SyncDatabase"     =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.};   //Last Sync setting used by the user while in an application. Database to connect to.
        ,"SyncNamespaces"   =>{"Type"=>"CV","Length"=>400,"Nullable"=>.t.};   //Last Sync setting used by the user while in an application. If blank all Namespaces (PostgreSQL schemas) will be loaded, otherwise list the Namespaces separated with ",".
        ,"SyncSetForeignKey"=>{"Type"=>"N","Length"=>1,"Nullable"=>.t.}};   //1="Not", 2="ForeignKeyRestrictions", 3="Onp_TableName", 4="Onfk_TableName", 5="OnTableName_id"   Last Sync setting used by the user while in an application.
                                      ,"Indexes"=>;
        {"fk_application"=>{"Expression"=>"fk_Application"};
        ,"fk_deployment" =>{"Expression"=>"fk_Deployment"};
        ,"fk_diagram"    =>{"Expression"=>"fk_Diagram"};
        ,"fk_user"       =>{"Expression"=>"fk_User"}}};
    ,"public.UserSettingModel"=>{"Fields"=>;
        {"pk"                =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"              =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"fk_User"           =>{"UsedAs"=>"Foreign","ParentTable"=>"public.User","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Model"          =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Model","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_ModelingDiagram"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.ModelingDiagram","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"}};   //Last Accessed Diagram, to help default the menu to restart on that diagram.
                                ,"Indexes"=>;
        {"fk_model"          =>{"Expression"=>"fk_Model"};
        ,"fk_modelingdiagram"=>{"Expression"=>"fk_ModelingDiagram"};
        ,"fk_user"           =>{"Expression"=>"fk_User"}}};
    ,"volatile.FileStream"=>{"Fields"=>;
        {"pk"            =>{"UsedAs"=>"Primary","Type"=>"I","Default"=>"Wharf-AutoIncrement()","AutoIncrement"=>.t.};
        ,"sysc"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"sysm"          =>{"Type"=>"DT","Scale"=>6,"Nullable"=>.t.};
        ,"type"          =>{"Type"=>"N","Length"=>1,"Nullable"=>.t.};   //1="ApplicationExport", 2="ApplicationImport", 3="ModelExport", 4="ModelImport", 5="TableExport"   
        ,"fk_User"       =>{"UsedAs"=>"Foreign","ParentTable"=>"public.User","Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Application"=>{"UsedAs"=>"Foreign","ParentTable"=>"public.Application","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Model"      =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Model","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"fk_Table"      =>{"UsedAs"=>"Foreign","ParentTable"=>"public.Table","ForeignKeyOptional"=>.t.,"Type"=>"I","Nullable"=>.t.,"OnDelete"=>"Cascade"};
        ,"LinkUID"       =>{"Type"=>"C","Length"=>36};
        ,"oid"           =>{"Type"=>"OID","Nullable"=>.t.};   //To the PostgreSQL Large Object.
        ,"FileName"      =>{"Type"=>"CV","Length"=>200,"Nullable"=>.t.}};
                            ,"Indexes"=>;
        {"fk_application"=>{"Expression"=>"fk_Application"};
        ,"fk_model"      =>{"Expression"=>"fk_Model"};
        ,"fk_table"      =>{"Expression"=>"fk_Table"};
        ,"fk_user"       =>{"Expression"=>"fk_User"}}};
    },;
"Enumerations"=>;
    {"public.APIEndpointStatus"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Active"         =>{"Order"=>1,"Number"=>1};
            ,"InactiveRemoved"=>{"Order"=>2,"Number"=>2}}};
    ,"public.APITokenAccessMode"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"ProjectAndApplicationSpecific"       =>{"Order"=>1,"Number"=>1};
            ,"AllProjectsAndApplicationsReadOnly"  =>{"Order"=>2,"Number"=>2};
            ,"AllProjectsAndApplicationsFullAccess"=>{"Order"=>3,"Number"=>3}}};
    ,"public.APITokenApplicationAccessLevel"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"None"                                             =>{"Order"=>1,"Number"=>1};
            ,"ReadOnly"                                         =>{"Order"=>2,"Number"=>2};
            ,"UpdateDescriptionandInformationEntries"           =>{"Order"=>3,"Number"=>3};
            ,"UpdateDescriptionandInformationEntriesandDiagrams"=>{"Order"=>4,"Number"=>4};
            ,"UpdateAnythingAndImportAndExport"                 =>{"Order"=>5,"Number"=>5};
            ,"UpdateAnythingAndSyncSchema"                      =>{"Order"=>6,"Number"=>6}}};
    ,"public.APITokenProjectAccessLevel"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"None"                                             =>{"Order"=>1,"Number"=>1};
            ,"ReadOnly"                                         =>{"Order"=>2,"Number"=>2};
            ,"UpdateDescriptionAndInformationEntries"           =>{"Order"=>3,"Number"=>3};
            ,"UpdateDescriptionandInformationEntriesAndDiagrams"=>{"Order"=>4,"Number"=>4};
            ,"UpdateAnything"                                   =>{"Order"=>5,"Number"=>5}}};
    ,"public.APITokenStatus"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Active"  =>{"Order"=>1,"Number"=>1};
            ,"Inactive"=>{"Order"=>2,"Number"=>2}}};
    ,"public.ApplicationDestructiveDelete"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"None"                    =>{"Order"=>1,"Number"=>1};
            ,"OnTablesTags"            =>{"Order"=>2,"Number"=>2};
            ,"OnNamespaces"            =>{"Order"=>3,"Number"=>3};
            ,"EntireApplicationContent"=>{"Order"=>4,"Number"=>4};
            ,"CanDeleteApplication"    =>{"Order"=>5,"Number"=>5}}};
    ,"public.BackendType"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"MariaDB"   =>{"Order"=>1,"Number"=>1};
            ,"MySQL"     =>{"Order"=>2,"Number"=>2};
            ,"PostgreSQL"=>{"Order"=>3,"Number"=>3};
            ,"MSSQL"     =>{"Order"=>4,"Number"=>4}}};
    ,"public.ColumnDefaultType"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>2,;
        "Values"=>;
            {"NotSet"       =>{"Order"=>1,"Number"=>0};
            ,"Custom"       =>{"Order"=>2,"Number"=>1};
            ,"Today"        =>{"Order"=>3,"Number"=>10};
            ,"Now"          =>{"Order"=>4,"Number"=>11};
            ,"RandomUuid"   =>{"Order"=>5,"Number"=>12};
            ,"False"        =>{"Order"=>6,"Number"=>13};
            ,"True"         =>{"Order"=>7,"Number"=>14};
            ,"AutoIncrement"=>{"Order"=>8,"Number"=>15}}};
    ,"public.ColumnOnDelete"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"NotSet"   =>{"Order"=>1,"Number"=>1};
            ,"Protect"  =>{"Order"=>2,"Number"=>2};
            ,"Cascade"  =>{"Order"=>3,"Number"=>3};
            ,"BreakLink"=>{"Order"=>4,"Number"=>4}}};
    ,"public.ColumnUsedAs"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Regular"   =>{"Order"=>1,"Number"=>1};
            ,"PrimaryKey"=>{"Order"=>2,"Number"=>2};
            ,"ForeignKey"=>{"Order"=>3,"Number"=>3};
            ,"Support"   =>{"Order"=>4,"Number"=>4}}};
    ,"public.CustomFieldStatus"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Active"  =>{"Order"=>1,"Number"=>1};
            ,"Inactive"=>{"Order"=>2,"Number"=>2};
            ,"Hidden"  =>{"Order"=>3,"Number"=>3}}};
    ,"public.CustomFieldTypes"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Logical"    =>{"Order"=>1,"Number"=>1};
            ,"MultiChoice"=>{"Order"=>2,"Number"=>2};
            ,"String"     =>{"Order"=>3,"Number"=>3};
            ,"TextArea"   =>{"Order"=>4,"Number"=>4};
            ,"Date"       =>{"Order"=>5,"Number"=>5}}};
    ,"public.CustomFieldUsedOn"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>2,;
        "Values"=>;
            {"Application"=>{"Order"=>1,"Number"=>1};
            ,"Namespace"  =>{"Order"=>2,"Number"=>2};
            ,"Table"      =>{"Order"=>3,"Number"=>3};
            ,"Column"     =>{"Order"=>4,"Number"=>4};
            ,"Model"      =>{"Order"=>5,"Number"=>5};
            ,"Entity"     =>{"Order"=>6,"Number"=>6};
            ,"Association"=>{"Order"=>7,"Number"=>7};
            ,"Package"    =>{"Order"=>8,"Number"=>8};
            ,"DataType"   =>{"Order"=>9,"Number"=>9};
            ,"Attribute"  =>{"Order"=>10,"Number"=>10}}};
    ,"public.DeploymentPasswordStorage"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Encrypted"            =>{"Order"=>1,"Number"=>1};
            ,"InConfigTxt"          =>{"Order"=>2,"Number"=>2};
            ,"InEnvironmentVariable"=>{"Order"=>3,"Number"=>3};
            ,"UserIsAWSIAMAccount"  =>{"Order"=>4,"Number"=>4}}};
    ,"public.DeploymentStatus"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Active"=>{"Order"=>1,"Number"=>1};
            ,"OnHold"=>{"Order"=>2,"Number"=>2}}};
    ,"public.DiagramNodeDisplayMode"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"TableNameAndAlias"=>{"Order"=>1,"Number"=>1};
            ,"TableAliasOrName" =>{"Order"=>2,"Number"=>2};
            ,"TableName"        =>{"Order"=>3,"Number"=>3}}};
    ,"public.DiagramRenderMode"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"VisJs"  =>{"Order"=>1,"Number"=>1};
            ,"mxgraph"=>{"Order"=>2,"Number"=>2}}};
    ,"public.DocStatus"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Missing"   =>{"Order"=>1,"Number"=>1};
            ,"NotNeeded" =>{"Order"=>2,"Number"=>2};
            ,"InProgress"=>{"Order"=>3,"Number"=>3};
            ,"Complete"  =>{"Order"=>4,"Number"=>4}}};
    ,"public.EnumerationImplementAs"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"NativeSQLEnum"=>{"Order"=>1,"Number"=>1};
            ,"Integer"      =>{"Order"=>2,"Number"=>2};
            ,"Numeric"      =>{"Order"=>3,"Number"=>3};
            ,"VarChar"      =>{"Order"=>4,"Number"=>4}}};
    ,"public.IndexAlgorithm"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"BTREE"=>{"Order"=>1,"Number"=>1}}};
    ,"public.KeyConfig"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Any"       =>{"Order"=>1,"Number"=>1};
            ,"Integer"   =>{"Order"=>2,"Number"=>2};
            ,"IntegerBig"=>{"Order"=>3,"Number"=>3}}};
    ,"public.LoginLogsStatus"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"LoggedIn"      =>{"Order"=>1,"Number"=>1};
            ,"UserLogout"    =>{"Order"=>2,"Number"=>2};
            ,"ImplicitLogout"=>{"Order"=>3,"Number"=>3}}};
    ,"public.ModelStage"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Proposed"    =>{"Order"=>1,"Number"=>1};
            ,"Draft"       =>{"Order"=>2,"Number"=>2};
            ,"Beta"        =>{"Order"=>3,"Number"=>3};
            ,"Stable"      =>{"Order"=>4,"Number"=>4};
            ,"InUse"       =>{"Order"=>5,"Number"=>5};
            ,"Discontinued"=>{"Order"=>6,"Number"=>6}}};
    ,"public.ProjectDestructiveDelete"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"None"                  =>{"Order"=>1,"Number"=>1};
            ,"OnEntitiesAssociations"=>{"Order"=>2,"Number"=>2};
            ,"CanDeleteModels"       =>{"Order"=>3,"Number"=>3}}};
    ,"public.SetForeignKey"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Not"                   =>{"Order"=>1,"Number"=>1};
            ,"ForeignKeyRestrictions"=>{"Order"=>2,"Number"=>2};
            ,"Onp_TableName"         =>{"Order"=>3,"Number"=>3};
            ,"Onfk_TableName"        =>{"Order"=>4,"Number"=>4};
            ,"OnTableName_id"        =>{"Order"=>5,"Number"=>5}}};
    ,"public.TagUseStatus"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"DoNotUse"    =>{"Order"=>1,"Number"=>1};
            ,"Active"      =>{"Order"=>2,"Number"=>2};
            ,"Discontinued"=>{"Order"=>3,"Number"=>3}}};
    ,"public.UsedBy"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"AllServers"    =>{"Order"=>1,"Number"=>1};
            ,"MySQLOnly"     =>{"Order"=>2,"Number"=>2};
            ,"PostgreSQLOnly"=>{"Order"=>3,"Number"=>3}}};
    ,"public.UserAccessMode"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"ProjectAndApplicationSpecific"       =>{"Order"=>1,"Number"=>1};
            ,"AllProjectsAndApplicationsReadOnly"  =>{"Order"=>2,"Number"=>2};
            ,"AllProjectsAndApplicationsFullAccess"=>{"Order"=>3,"Number"=>3};
            ,"RootAdmin"                           =>{"Order"=>4,"Number"=>4}}};
    ,"public.UserApplicationAccessLevel"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"None"                                           =>{"Order"=>1,"Number"=>1};
            ,"ReadOnly"                                       =>{"Order"=>2,"Number"=>2};
            ,"EditDescriptionAndInformationEntries"           =>{"Order"=>3,"Number"=>3};
            ,"EditDescriptionAndInformationEntriesAndDiagrams"=>{"Order"=>4,"Number"=>4};
            ,"EditAnythingAndImportExport"                    =>{"Order"=>5,"Number"=>5};
            ,"EditAnythingAndSyncSchema"                      =>{"Order"=>6,"Number"=>6};
            ,"FullAccess"                                     =>{"Order"=>7,"Number"=>7}}};
    ,"public.UserProjectAccessLevel"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"None"                                           =>{"Order"=>1,"Number"=>1};
            ,"ReadOnly"                                       =>{"Order"=>2,"Number"=>2};
            ,"EditDescriptionAndInformationEntries"           =>{"Order"=>3,"Number"=>3};
            ,"EditDescriptionAndInformationEntriesAndDiagrams"=>{"Order"=>4,"Number"=>4};
            ,"EditAnything"                                   =>{"Order"=>5,"Number"=>5};
            ,"FullAccess"                                     =>{"Order"=>6,"Number"=>7}}};
    ,"public.UserSettingValueType"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"String"  =>{"Order"=>1,"Number"=>1};
            ,"Integer" =>{"Order"=>2,"Number"=>2};
            ,"Date"    =>{"Order"=>3,"Number"=>3};
            ,"BlobMemo"=>{"Order"=>4,"Number"=>4}}};
    ,"public.UserStatus"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Active"  =>{"Order"=>1,"Number"=>1};
            ,"Inactive"=>{"Order"=>2,"Number"=>2}}};
    ,"public.UseStatus"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"Unknown"         =>{"Order"=>1,"Number"=>1};
            ,"Proposed"        =>{"Order"=>2,"Number"=>2};
            ,"UnderDevelopment"=>{"Order"=>3,"Number"=>3};
            ,"Active"          =>{"Order"=>4,"Number"=>4};
            ,"ToBeDiscontinued"=>{"Order"=>5,"Number"=>5};
            ,"Discontinued"    =>{"Order"=>6,"Number"=>6}}};
    ,"public.ValueType"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"String"  =>{"Order"=>1,"Number"=>1};
            ,"Integer" =>{"Order"=>2,"Number"=>2};
            ,"Date"    =>{"Order"=>3,"Number"=>3};
            ,"BlobMemo"=>{"Order"=>4,"Number"=>4}}};
    ,"volatile.FileStreamType"=>{;
        "ImplementAs"=>"Numeric",;
        "ImplementLength"=>1,;
        "Values"=>;
            {"ApplicationExport"=>{"Order"=>1,"Number"=>1};
            ,"ApplicationImport"=>{"Order"=>2,"Number"=>2};
            ,"ModelExport"      =>{"Order"=>3,"Number"=>3};
            ,"ModelImport"      =>{"Order"=>4,"Number"=>4};
            ,"TableExport"      =>{"Order"=>5,"Number"=>5}}};
    };
}
