name: build_datawharf_docker_base_image

on:
  push:
    branches:
      - "main"

  #The following run a workflow when someone stars a repository, but later only the repo owner can do the build
  watch:
    types: [started]

jobs:
  build:
  #To see what is installed on the runs-on go to https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04

    #The following prevents to execute the action by others and only by maintainers for example.
    if: github.actor == github.event.repository.owner.login

    #The job named "build" has several steps
    steps:
    
    - name: Checkout DataWharf
      uses: actions/checkout@v3
      with:
        repository: EricLendvai/DataWharf
        path: main

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./main/Dockerfile_DockerHub_Base_Image_Ubuntu_22_04
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/dockerfile_dockerhub_base_image_ubuntu_22_04:latest