version: '3'

services:
  ############
  # postgres #
  ############
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      # Might be real POSTGRES variables
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data


  #############
  # datawharf #
  #############
  datawharf:
    container_name: datawharf
    build:
      context: .
      dockerfile: hosting/docker/Dockerfile-Ubuntu
      target: datawharf
    image: datawharf_demo_using_dockerhub_baseimage:latest
    ports:
      - "8080:80"
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
